name: Build mROS Cooler UI ISO

env:
  api_key: ${{ secrets.GITHUB_TOKEN }}
  name: ${{ github.event.repository.name }}
  release_name: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged

    steps:
      - name: Set up environment
        run: echo "Setting up environment..."

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Required Packages
        run: |
          echo "Installing required packages..."
          pacman -Sy
          pacman --noconfirm -S git archiso python python-pygithub reflector
          pacman --noconfirm -S linux-latest=6.1
          pacman --noconfirm -S xfce4 gnome kde plasma

      - name: Configure Mirrorlist
        run: |
          echo "Configuring mirrorlist..."
          reflector -c "US" -f 12 -l 10 -n 12 --save /etc/pacman.d/mirrorlist

      - name: Build ISO Image
        run: |
          echo "Building ISO image..."
          mkarchiso -v iso/

      - name: Upload ISO to Release
        run: |
          echo "Uploading ISO to release..."
          python tools/upload_asset.py

      - name: Notify Build Completion
        run: echo "Build process completed successfully! 🚀"
